name: merkletree
description: A Dart implementation of the merkle tree able to construct and verify merkle trees.
version: 1.0.3
homepage: https://github.com/ethereumdart/merkletree
author: Peter Chung <touhonoob@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  buffer: ^1.0.6

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.2
  pointycastle: ^1.0.1
  convert: ^2.1.1
