name: merkletree
description: Construct Merkle Trees and verify proofs in Dart.
version: 1.0.1
homepage: https://github.com/ethereumdart/merkletree
author: Peter Chung <touhonoob@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  buffer: ^1.0.6

dev_dependencies:
  test: ^1.6.2
  pointycastle: ^1.0.1
  convert: ^2.1.1
